import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Examples | Nexora - AI Competitor Intelligence',
  description: 'Explore real-world competitor analysis reports generated by Nexora. See how top brands stay ahead of the curve.',
}

export default function ExamplesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
